"""The tests in this module are only ran to ensure the metric breakdown
reported in the arxiv paper have not changed.
"""

import pickle
from pathlib import Path
from typing import ClassVar, Literal

import numpy as np
import pytest
from numpy.testing import assert_array_equal

from psiq_fh.wb_program import FermiHubbardQreRunner, QreAnalysis
from psiq_fh.wb_program._runner import PLOT_PATHWAY
from psiq_fh.wb_program.utils import extract_all

BASELINE: str = "baseline"
IMPROVED: str = "improved"

LATTICE_SIZES = range(4, 21, 2)
N_HWP_BATCHES = 1
FIXTURE_PATH = Path(__file__).parent

TOTAL_AV = {
    BASELINE: np.array(
        [
            96612513.0,
            101371616.25,
            104901404.0,
            114530324.0,
            133267412.25,
            132709789.5,
            136856199.0,
            152164417.0,
            161241011.5,
        ]
    ),
    IMPROVED: np.array(
        [
            43803797.75,
            39608745.25,
            37412418.25,
            38479960.25,
            41870063.875,
            38626157.125,
            38463894.875,
            41306376.5,
            41416680.5,
        ]
    ),
}

TOTAL_CLIFF_AV = {
    BASELINE: np.array([41375268, 53111850, 60261168, 70516656, 86110902, 90019254, 94610364, 108668988, 118319100]),
    IMPROVED: np.array([1327977, 1285563, 1218593, 1256529, 1349259, 1221547, 1195413, 1260037, 1244981]),
}
TOTAL_NONCLIFF_AV = {
    BASELINE: np.array(
        [43654656.0, 42937344.0, 41678976.0, 42409728.0, 46006848.0, 41813856.0, 41359104.0, 42893280.0, 42499104.0]
    ),
    IMPROVED: np.array([1587129, 1293096, 1138487, 1131791, 1190214, 1065846, 1036422, 1087990, 1073478]),
}

TOTAL_BB_AV = {
    BASELINE: np.array(
        [11582589.0, 5322422.25, 2961260.0, 1603940.0, 1149662.25, 876679.5, 886731.0, 602149.0, 422807.5]
    ),
    IMPROVED: np.array(
        [
            40888691.75,
            37030086.25,
            35055338.25,
            36091640.25,
            39330590.875,
            36338764.125,
            36232059.875,
            38958349.5,
            39098221.5,
        ]
    ),
}


@pytest.fixture(scope="class")
def runner(request):
    """Create one runner for each fidelity-test variant."""
    return FermiHubbardQreRunner(
        lattice_sizes=LATTICE_SIZES,
        variant=request.cls.VARIANT,
        num_batches=N_HWP_BATCHES,
    )


@pytest.fixture(scope="class")
def metrics_data(request, runner):
    reporter = request.config.pluginmanager.get_plugin("terminalreporter")
    capture_manager = request.config.pluginmanager.get_plugin("capturemanager")
    if reporter is not None and capture_manager is not None:
        with capture_manager.global_and_fixture_disabled():
            reporter.write_line(
                f"Generating {request.cls.VARIANT} metrics; this takes about 2 minutes...",
                yellow=True,
            )
            reporter.flush()

    return runner.retrieve(save_callgraphs=True)


@pytest.fixture(scope="class")
def ground_truth_callgraph_data(request):
    """Load the callgraphs used to generate the paper's plots."""
    fixture = FIXTURE_PATH / f"{request.cls.VARIANT}_callgraph_data.pkl"
    with fixture.open("rb") as file:
        return pickle.load(file)


@pytest.fixture(scope="class")
def generated_callgraph_data(request, metrics_data):
    """Load the callgraphs generated by the metrics fixture."""
    variant = request.cls.VARIANT
    callgraph_path = PLOT_PATHWAY / f"{variant}_callgraph_data" / f"{N_HWP_BATCHES}batches"
    return {
        lattice_size: QreAnalysis.from_json(
            callgraph_path / f"{variant}_{lattice_size}dim_{N_HWP_BATCHES}batches.qre_analysis"
        )
        for lattice_size in LATTICE_SIZES
    }


@pytest.mark.paper_fidelity
class PaperFidelityTests:
    VARIANT: ClassVar[Literal["baseline", "improved"]]

    def test_total_av(self, metrics_data):
        assert_array_equal(TOTAL_AV[self.VARIANT], extract_all(metrics_data, "total_av"))

    def test_total_clifford_av(self, metrics_data):
        assert_array_equal(TOTAL_CLIFF_AV[self.VARIANT], extract_all(metrics_data, "aggregated_clifford_av"))

    def test_total_nonclifford_av(self, metrics_data):
        assert_array_equal(TOTAL_NONCLIFF_AV[self.VARIANT], extract_all(metrics_data, "aggregated_non_clifford_av"))

    def test_black_box_rotation(self, metrics_data):
        assert_array_equal(TOTAL_BB_AV[self.VARIANT], extract_all(metrics_data, "black_box_av"))

    @pytest.mark.parametrize("lattice_size", LATTICE_SIZES)
    def test_active_volume_breakdown(self, lattice_size, ground_truth_callgraph_data, generated_callgraph_data):
        granularity: tuple[str, ...] = (
            ("PhasingCircuit",) if self.VARIANT == BASELINE else ("PhasingCircuit", "DirectionalPhasingCircuit")
        )
        expected = ground_truth_callgraph_data[lattice_size].decompose_metric_cost("active_volume", granularity)
        current = generated_callgraph_data[lattice_size].decompose_metric_cost("active_volume", granularity)
        assert expected == current


class TestBaselineFidelity(PaperFidelityTests):
    VARIANT = BASELINE


class TestImprovedFidelity(PaperFidelityTests):
    VARIANT = IMPROVED
