"""Code generated by ChatGPT to post-process callgraph data to plot AV breakdown of select subroutines."""

from __future__ import annotations

import re
from collections import OrderedDict, defaultdict
from collections.abc import Mapping
from numbers import Real

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.axes import Axes


def extract_additive_components(
    data,
    *,
    parent="root",
    metric="active_volume",
    stop_at=("PhasingCircuit",),
    aggregate=True,
    clean_names=True,
    include_zero=False,
):
    """
    Extract a non-overlapping metric decomposition.

    Normal nodes contribute their ``self`` value.

    Nodes whose names match ``stop_at`` contribute their ``total`` value,
    and their descendants are not traversed. This lets a subroutine absorb
    all synthesized work below it.
    """
    nodes = data["nodes"]
    by_id = {node["id"]: node for node in nodes}

    if parent in by_id:
        parent_node = by_id[parent]
    else:
        matches = [node for node in nodes if node.get("name") == parent]

        if not matches:
            raise KeyError(f"No node found for {parent!r}.")

        if len(matches) > 1:
            raise ValueError(f"Multiple nodes are named {parent!r}; use the full node ID.")

        parent_node = matches[0]

    def cleaned_name(name):
        if not clean_names:
            return name

        return re.sub(r"_(?:un)?compute_\d+$", "", name)

    def should_stop(node):
        return any(substring in node.get("name", "") for substring in stop_at)

    selected = []
    stack = [parent_node["id"]]
    visited = set()

    while stack:
        node_id = stack.pop()

        if node_id in visited:
            continue
        visited.add(node_id)

        node = by_id[node_id]
        node_name = cleaned_name(node["name"])

        if should_stop(node):
            # Absorb all descendant work into this component.
            value = float(node["metrics"][metric]["total"])
            selected.append((node_name, value))
            continue

        # Otherwise count only this node's exclusive contribution.
        value = float(node["metrics"][metric]["self"])
        selected.append((node_name, value))

        stack.extend(node.get("children", []))

    expected_total = float(parent_node["metrics"][metric]["total"])

    if aggregate:
        components = defaultdict(float)

        for name, value in selected:
            if include_zero or value != 0:
                components[name] += value

        components = dict(components)

    else:
        components = {
            f"{index}:{name}": value for index, (name, value) in enumerate(selected) if include_zero or value != 0
        }

    actual_total = sum(components.values())

    if not abs(actual_total - expected_total) < 1e-9:
        raise ValueError(
            "Component sum does not match parent total:\n"
            f"  Sum:        {actual_total:,.3f}\n"
            f"  Expected:   {expected_total:,.3f}\n"
            f"  Difference: {actual_total - expected_total:,.3f}"
        )

    return components


def plot_stacked_metric(
    components: Mapping[str, Real],
    *,
    total: Real | None = None,
    title: str = "Active Volume Breakdown",
    ylabel: str = "Active Volume",
    bar_label: str = "Total",
    sort: bool = True,
    legend_top_to_bottom: bool = True,
    show_percentages: bool = True,
    legend_title: str = "Component",
    figsize: tuple[float, float] = (10, 8),
    tolerance: float = 1e-9,
    ax: Axes | None = None,
) -> Axes:
    """
    Plot a dictionary of additive metric components as one stacked bar.

    Parameters
    ----------
    components
        Mapping from component name to its non-overlapping contribution.
        For a call graph, these should normally be aggregated ``self`` values.

    total
        Expected overall total. When supplied, the function checks that the
        component sum matches this value.

    sort
        If True, place the largest component at the bottom of the stack.

    legend_top_to_bottom
        If True, order the legend to match the visible stack from top to
        bottom. If False, the legend follows the stack from bottom to top.

    show_percentages
        Include each component's percentage in the legend.

    tolerance
        Relative and absolute tolerance used when comparing the component sum
        to ``total``.

    ax
        Existing Matplotlib axes. A new figure is created when omitted.

    Returns
    -------
    matplotlib.axes.Axes
        The axes containing the plot.
    """
    if not components:
        raise ValueError("components must contain at least one entry.")

    cleaned_components: list[tuple[str, float]] = []

    for name, value in components.items():
        if not isinstance(value, Real):
            raise TypeError(f"Component {name!r} has a non-numeric value: {value!r}.")

        numeric_value = float(value)

        if numeric_value < 0:
            raise ValueError(f"Component {name!r} has a negative value: {numeric_value}.")

        if numeric_value != 0:
            cleaned_components.append((str(name), numeric_value))

    if not cleaned_components:
        raise ValueError("All component values are zero.")

    if sort:
        cleaned_components.sort(
            key=lambda item: item[1],
            reverse=True,
        )

    component_sum = sum(value for _, value in cleaned_components)

    if total is None:
        expected_total = component_sum
    else:
        expected_total = float(total)

        difference = component_sum - expected_total
        allowed_error = tolerance * max(
            1.0,
            abs(component_sum),
            abs(expected_total),
        )

        if abs(difference) > allowed_error:
            raise ValueError(
                "Components do not sum to the expected total:\n"
                f"  Sum:        {component_sum:,.6g}\n"
                f"  Expected:   {expected_total:,.6g}\n"
                f"  Difference: {difference:,.6g}"
            )

    if ax is None:
        _, ax = plt.subplots(figsize=figsize)

    cmap = plt.get_cmap("tab20")
    bottom = 0.0
    handles = []
    labels = []

    for index, (name, value) in enumerate(cleaned_components):
        bar = ax.bar(
            bar_label,
            value,
            bottom=bottom,
            width=0.7,
            color=cmap(index % cmap.N),
            edgecolor="black",
            linewidth=0.4,
        )

        handles.append(bar[0])

        if show_percentages:
            percentage = 100 * value / component_sum
            labels.append(f"{name}: {value:,.0f} ({percentage:.1f}%)")
        else:
            labels.append(f"{name}: {value:,.0f}")

        bottom += value

    # Bars are drawn bottom-to-top. Reverse the legend so its first entry
    # corresponds to the top visible segment of the stack.
    if legend_top_to_bottom:
        handles = handles[::-1]
        labels = labels[::-1]

    ax.legend(
        handles,
        labels,
        title=legend_title,
        bbox_to_anchor=(1.02, 1),
        loc="upper left",
        borderaxespad=0,
        frameon=False,
    )

    ax.set_title(title)
    ax.set_ylabel(ylabel)
    ax.set_ylim(0, expected_total * 1.03)
    ax.ticklabel_format(
        axis="y",
        style="sci",
        scilimits=(0, 0),
    )

    ax.text(
        0,
        expected_total,
        f"{expected_total:,.0f}",
        ha="center",
        va="bottom",
        fontsize=9,
    )

    ax.figure.tight_layout()

    return ax


def group_active_volume_components(
    components: dict[str, float],
    *,
    groups: dict[str, tuple[str, ...]] | None = None,
    others_label: str = "Other",
) -> dict[str, float]:
    """
    Group active-volume components by substrings in their names.

    Each component is assigned to the first matching group. Components that
    match no group are combined under ``others_label``.
    """
    if groups is None:
        groups = {
            "FermionicSwap": ("FermionicSwap",),
            "ComputeHammingWeight": ("ComputeHammingWeight",),
            "PhasingCircuit": ("PhasingCircuit",),
            "TwoModeFFFT": ("TwoModeFFFT",),
        }

    grouped = OrderedDict((label, 0.0) for label in groups)
    grouped[others_label] = 0.0

    for component_name, value in components.items():
        for label, substrings in groups.items():
            if any(substring in component_name for substring in substrings):
                grouped[label] += float(value)
                break
        else:
            grouped[others_label] += float(value)

    # Remove empty groups while preserving the order.
    return {label: value for label, value in grouped.items() if value != 0}


def plot_av_breakdown_over_lattice_sizes(
    graphs,
    lattice_sizes,
    *,
    parent="root",
    metric="active_volume",
    stop_at=("PhasingCircuit",),
    groups=None,
    others_label="Other",
    title="Active volume breakdown",
    ylabel="Active volume",
    legend_top_to_bottom=True,
    show_percentages=False,
    ax=None,
    figsize=(8, 6),
    ylim_high=None,
    show_legend=True,
    show_xlabel=True,
    show_ylabel=True,
):
    """
    Plot a stacked active-volume breakdown for multiple call graphs.

    Parameters
    ----------
    graphs
        Sequence of call-graph dictionaries, one per lattice size.

    lattice_sizes
        Sequence of lattice sizes corresponding to ``graphs``.

    parent
        Node ID or unique node name at which to start each decomposition.

    metric
        Metric to extract.

    stop_at
        Node-name substrings at which traversal stops. A matching node
        contributes its ``total`` value, including all synthesized work below
        it. For example, stopping at ``PhasingCircuit`` folds rotation
        synthesis beneath it into the PhasingCircuit category.

    groups
        Mapping from displayed category to component-name substrings.

    others_label
        Category for unmatched components.

    show_percentages
        If True, place percentages inside sufficiently large stack sections.

    Returns
    -------
    matplotlib.axes.Axes
    """
    if groups is None:
        groups = OrderedDict(
            [
                ("FermionicSwap", ("FermionicSwap",)),
                (
                    "ComputeHammingWeight",
                    ("ComputeHammingWeight",),
                ),
                ("PhasingCircuit", ("PhasingCircuit",)),
                ("TwoModeFFFT", ("TwoModeFFFT",)),
            ]
        )

    if len(graphs) != len(lattice_sizes):
        raise ValueError("graphs and lattice_sizes must have the same length.")

    category_names = [*groups, others_label]
    breakdowns = []
    expected_totals = []

    for lattice_size, graph in zip(lattice_sizes, graphs):
        components = extract_additive_components(
            graph,
            parent=parent,
            metric=metric,
            stop_at=stop_at,
            aggregate=True,
            include_zero=False,
        )

        grouped = group_active_volume_components(
            components,
            groups=groups,
            others_label=others_label,
        )

        # Ensure every graph has the same category keys.
        grouped = {category: float(grouped.get(category, 0.0)) for category in category_names}

        expected_total = float(
            next(node for node in graph["nodes"] if node["id"] == parent)["metrics"][metric]["total"]
        )

        actual_total = sum(grouped.values())

        if not np.isclose(actual_total, expected_total):
            raise ValueError(
                f"Lattice size {lattice_size}: grouped components "
                f"sum to {actual_total:,.3f}, but the graph total is "
                f"{expected_total:,.3f}."
            )

        breakdowns.append(grouped)
        expected_totals.append(expected_total)

    x = np.arange(len(lattice_sizes))
    bottoms = np.zeros(len(lattice_sizes), dtype=float)

    if ax is None:
        _, ax = plt.subplots(figsize=figsize)

    cmap = plt.get_cmap("Set2")

    handles = []
    labels = []

    for index, category in enumerate(category_names):
        values = np.array(
            [breakdown[category] for breakdown in breakdowns],
            dtype=float,
        )

        bars = ax.bar(
            x,
            values,
            bottom=bottoms,
            width=0.7,
            label=category,
            color=cmap(index % cmap.N),
            edgecolor="black",
            linewidth=0.7,
        )

        handles.append(bars[0])
        labels.append(category)

        if show_percentages:
            totals = np.asarray(expected_totals)

            for bar, value, bottom, total in zip(
                bars,
                values,
                bottoms,
                totals,
            ):
                percentage = 100 * value / total

                # Avoid unreadable labels in very small sections.
                if percentage >= 4:
                    ax.text(
                        bar.get_x() + bar.get_width() / 2,
                        bottom + value / 2,
                        f"{percentage:.1f}%",
                        ha="center",
                        va="center",
                        fontsize=14,
                        rotation=90,
                    )

        bottoms += values

    if legend_top_to_bottom:
        handles = handles[::-1]
        labels = labels[::-1]

    if show_legend:
        ax.legend(
            handles,
            labels,
            title="Subroutine",
            frameon=True,
        )

    if ylim_high:
        ax.set_ylim(0, ylim_high)

    ax.set_xticks(x)
    ax.set_xticklabels(lattice_sizes)
    if show_xlabel:
        ax.set_xlabel("Lattice size")
    if show_ylabel:
        ax.set_ylabel(ylabel)
    ax.set_title(title, fontsize=24)

    ax.ticklabel_format(
        axis="y",
        style="sci",
        scilimits=(0, 0),
    )

    ax.grid(axis="y", alpha=1, linestyle=":")
    ax.set_axisbelow(True)
    ax.figure.tight_layout()

    return ax
