"""Tests for jordan-wigner ordering utils."""

import pytest

import numpy as np

from psiq_fh.utils.jw_ordering_utils import (
    pink_happy_enum,
    generate_even_odd_enum,
    generate_high_low_enum,
    validate_enumerations,
    generate_interaction_enumeration_indices,
    generate_plaquette_enumeration_indices,
    shift_enumeration,
    get_plaqs,
)


def is_mod4_group(plaquette):
    """Check all 4 mod 4 values are unique (i.e., 0,1,2,3 in some order)."""
    mods = [x % 4 for x in plaquette.flatten()]
    return sorted(mods) == [0, 1, 2, 3]


def is_circular_ordered(plaquette):
    """Check if elements increase in a clockwise or anticlockwise order. Any other ordering would be incorrect."""
    a, b = plaquette[0, 0], plaquette[0, 1]
    d, c = plaquette[1, 0], plaquette[1, 1]

    clockwise = [b, c, d, a]
    anticlockwise = [a, d, c, b]

    return (clockwise == sorted(clockwise)) or (anticlockwise == sorted(anticlockwise))


@pytest.mark.parametrize("lattice_size", [4, 12])
def test_pink_happy_enum_single_spin(lattice_size):
    """Test pink plaquettes are localized in the enumeration generated by pink_happy_enum function."""
    pink_localized_enumeration = pink_happy_enum(lattice_size, lattice_size)
    plaquette_array = get_plaqs([pink_localized_enumeration])
    for idx, plaq in enumerate(plaquette_array):
        assert is_mod4_group(plaq), f"Plaquette {idx} has inconsistent mod 4 values:\n{plaq}"
        assert is_circular_ordered(plaq), f"Plaquette {idx} is not ordered clockwise or anticlockwise:\n{plaq}"


@pytest.mark.parametrize("lattice_size", [4, 12])
def test_generate_even_odd_enum_function(lattice_size):
    """Test generate_even_odd_enum function."""
    spin_up_enumeration, spin_down_enumeration = generate_even_odd_enum(lattice_size)

    # Check shape of enumeration is as expected
    assert spin_up_enumeration.shape == (
        lattice_size,
        lattice_size,
    ), f"Expected shape ({lattice_size}, {lattice_size}), got {spin_up_enumeration.shape}"
    assert spin_down_enumeration.shape == (
        lattice_size,
        lattice_size,
    ), f"Expected shape ({lattice_size}, {lattice_size}), got {spin_down_enumeration.shape}"

    # Check that the spin up enumeration contains all even indices as expected
    up_flattened = spin_up_enumeration.flatten()
    up_expected = np.arange(0, 2 * lattice_size * lattice_size, 2)
    assert np.array_equal(np.sort(up_flattened), up_expected), (
        f"Spin up enumeration does not contain all even integers from 0 to "
        f"{2 * lattice_size * lattice_size - 2} exactly once.\n"
        f"Got: {np.sort(up_flattened)}"
    )

    # Check that the spin down enumeration contains all odd indices as expected
    down_flattened = spin_down_enumeration.flatten()
    down_expected = np.arange(1, 2 * lattice_size * lattice_size, 2)
    assert np.array_equal(np.sort(down_flattened), down_expected), (
        f"Spin down enumeration does not contain all odd integers from 1 to "
        f"{2 * lattice_size * lattice_size - 1} exactly once.\n"
        f"Got: {np.sort(down_flattened)}"
    )


@pytest.mark.parametrize("lattice_size", range(4, 22, 2))
@pytest.mark.parametrize("pink_happy", [True, False])
def test_generate_high_low_enum_function(lattice_size, pink_happy):
    """Test generate_high_low_enum function."""
    spin_up_enumeration, spin_down_enumeration = generate_high_low_enum(lattice_size, pink_happy=pink_happy)

    # Check shape of enumeration is as expected
    assert spin_up_enumeration.shape == (
        lattice_size,
        lattice_size,
    ), f"Expected shape ({lattice_size}, {lattice_size}), got {spin_up_enumeration.shape}"
    assert spin_down_enumeration.shape == (
        lattice_size,
        lattice_size,
    ), f"Expected shape ({lattice_size}, {lattice_size}), got {spin_down_enumeration.shape}"

    # Check that the spin up enumeration contains the low indices as expected
    up_flattened = spin_up_enumeration.flatten()
    up_expected = np.arange(lattice_size * lattice_size)
    assert np.array_equal(np.sort(up_flattened), up_expected), (
        f"Spin up enumeration does not contain all integers from 0 to {lattice_size**2 - 1} exactly once.\nGot: {np.sort(up_flattened)}"
    )

    # Check that the spin down enumeration contains the high indices as expected
    down_flattened = spin_down_enumeration.flatten()
    down_expected = np.arange(lattice_size * lattice_size, 2 * lattice_size * lattice_size)
    assert np.array_equal(np.sort(down_flattened), down_expected), (
        f"Spin down enumeration does not contain all integers from {lattice_size**2} to {2 * lattice_size**2 - 1} exactly once.\nGot: {np.sort(down_flattened)}"
    )


@pytest.mark.parametrize("lattice_size", range(4, 22, 2))
def test_generate_high_low_enum_pink_localized(lattice_size):
    """Test generate_high_low_enum function with the pink_happy flag set to True to check localized plaquettes."""
    up, down = generate_high_low_enum(lattice_size, pink_happy=True)
    plaquette_array = get_plaqs([up, down])
    for idx, plaq in enumerate(plaquette_array):
        assert is_mod4_group(plaq), f"Plaquette {idx} has inconsistent mod 4 values:\n{plaq}"
        assert is_circular_ordered(plaq), f"Plaquette {idx} is not ordered clockwise or anticlockwise:\n{plaq}"


@pytest.mark.parametrize(
    "test_enumeration, test_shifted",
    [
        (
            np.array([[3, 6, 4, 5], [1, 9, 11, 15], [21, 36, 42, 90], [0, 7, 18, 88]]),
            np.array([[9, 11, 15, 1], [36, 42, 90, 21], [7, 18, 88, 0], [6, 4, 5, 3]]),
        )
    ],
)
def test_shift_enumeration_function(test_enumeration, test_shifted):
    """Function tested just with an example of what we want this shift to do."""
    function_shifted = shift_enumeration(test_enumeration)
    assert np.array_equal(function_shifted, test_shifted)


def test_validate_enumerations_raises_for_invalid_enumerations():
    """Check invalid enumerations are caught by checker function."""
    with pytest.raises(ValueError, match="Currently only 1 or 2 spin sectors supported."):
        # invalid enumeration with 0 spin sectors
        validate_enumerations([])

    with pytest.raises(ValueError, match="Currently only 1 or 2 spin sectors supported."):
        # invalid enumeration with 3 spin sectors
        validate_enumerations([np.array([[0]]), np.array([[1]]), np.array([[2]])])

    with pytest.raises(ValueError, match="All enumerations must have the same shape"):
        # invalid enumeration where different spin sectors have different shapes
        validate_enumerations([np.array([[0]]), np.array([[1, 2]])])

    with pytest.raises(ValueError, match="Duplicated indices found in enumerations."):
        # invalid enumeration with duplicated index in one spin sector
        validate_enumerations([np.array([[0, 0]])])

    with pytest.raises(ValueError, match="Duplicated indices found in enumerations."):
        # invalid enumeration with duplicated index across spin sectors
        validate_enumerations([np.array([[0]]), np.array([[0]])])


@pytest.mark.parametrize("lattice_size", [4, 12])
def test_generate_interaction_enumeration_indices_even_odd(lattice_size):
    """Check interaction indices obtained from the even-odd JW ordering are as expected."""
    spin_up_enumeration, spin_down_enumeration = generate_even_odd_enum(lattice_size)
    indices = generate_interaction_enumeration_indices([spin_up_enumeration, spin_down_enumeration])
    expected_indices = [[2 * i, (2 * i) + 1] for i in range(lattice_size**2)]
    assert len(indices) == lattice_size**2
    assert indices == expected_indices


@pytest.mark.parametrize("lattice_size", [4, 12])
@pytest.mark.parametrize("pink_happy", [True, False])
def test_generate_interaction_enumeration_indices_high_low(lattice_size, pink_happy):
    """Check interaction indices obtained from the high-low JW ordering are as expected."""
    spin_up_enumeration, spin_down_enumeration = generate_high_low_enum(lattice_size, pink_happy=pink_happy)
    indices = generate_interaction_enumeration_indices([spin_up_enumeration, spin_down_enumeration])
    expected_indices = [[i, i + lattice_size**2] for i in range(lattice_size**2)]
    assert len(indices) == lattice_size**2
    assert sorted(indices) == sorted(expected_indices)


@pytest.mark.parametrize(
    "lattice_size, expected_indices",
    [
        (2, [[0, 4, 6, 2], [1, 5, 7, 3]]),
        (
            4,
            [
                [0, 8, 10, 2],
                [1, 9, 11, 3],
                [4, 12, 14, 6],
                [5, 13, 15, 7],
                [16, 24, 26, 18],
                [17, 25, 27, 19],
                [20, 28, 30, 22],
                [21, 29, 31, 23],
            ],
        ),
    ],
)
def test_generate_plaquette_enumeration_indices_for_even_odd_enum_pink_plaq(lattice_size, expected_indices):
    """Check pink plaquette indices obtained from the even-odd JW ordering are as expected"""
    spin_up_enumeration, spin_down_enumeration = generate_even_odd_enum(lattice_size)
    pink_indices = generate_plaquette_enumeration_indices([spin_up_enumeration, spin_down_enumeration], color="pink")
    assert sorted(pink_indices) == sorted(expected_indices)


@pytest.mark.parametrize(
    "enumeration, expected_indices",
    [
        ([np.array([[0, 1, 2, 3], [4, 5, 6, 7]])], [[0, 4, 5, 1], [2, 6, 7, 3]]),
        ([np.array([[0, 3, 4, 5], [1, 2, 7, 6]])], [[0, 1, 2, 3], [4, 7, 6, 5]]),
    ],
)
def test_generate_plaquette_enumeration_indices_for_arbitrary_enum_pink_plaq(enumeration, expected_indices):
    """Test action of generate_plaquette_enumeration_indices function against arbitrary enumerations."""
    pink_indices = generate_plaquette_enumeration_indices(enumeration, color="pink")
    print("pink", pink_indices)
    assert sorted(pink_indices) == sorted(expected_indices)


@pytest.mark.parametrize(
    "lattice_size",
    [4, 12],
)
def test_generate_plaquette_enumeration_indices_high_low_enum_pink_happy(lattice_size):
    spin_up_enumeration, spin_down_enumeration = generate_high_low_enum(lattice_size, pink_happy=True)
    pink_indices = generate_plaquette_enumeration_indices([spin_up_enumeration, spin_down_enumeration], color="pink")
    assert len(pink_indices) == lattice_size**2 / 2
    for idx, plaq in enumerate(pink_indices):
        # Check pink plaquettes localized as expected.
        assert len(plaq) == 4
        assert sorted(plaq) == list(range(min(plaq), min(plaq) + 4)), f"Pink plaquette {idx} is not localized: {plaq}"
    # Now check gold indices
    gold_indices = generate_plaquette_enumeration_indices([spin_up_enumeration, spin_down_enumeration], color="gold")
    assert len(gold_indices) == lattice_size**2 / 2
    for idx, plaq in enumerate(gold_indices):
        # Check gold plaquettes not localized as expected.
        assert len(plaq) == 4
        assert sorted(plaq) != list(range(min(plaq), min(plaq) + 4)), f"Gold plaquette {idx} is localized: {plaq}"


@pytest.mark.parametrize(
    "lattice_size,expected_indices",
    [
        (2, []),
        (
            4,
            [
                [10, 18, 20, 12],
                [11, 19, 21, 13],
                [14, 22, 16, 8],
                [15, 23, 17, 9],
                [26, 2, 4, 28],
                [27, 3, 5, 29],
                [30, 6, 0, 24],
                [31, 7, 1, 25],
            ],
        ),
    ],
)
def test_generate_plaquette_enumeration_indices_for_even_odd_enum_gold_plaq(lattice_size, expected_indices):
    """Check gold plaquette indices obtained from the even-odd JW ordering are as expected"""
    spin_up_enumeration, spin_down_enumeration = generate_even_odd_enum(lattice_size)
    gold_indices = generate_plaquette_enumeration_indices([spin_up_enumeration, spin_down_enumeration], color="gold")
    assert sorted(gold_indices) == sorted(expected_indices)


def are_neighbors(plaq, enumeration):
    """Check if all values in the 2x2 plaquette come from a valid sub-block of the given enumeration."""
    for i in range(enumeration.shape[0] - 1):
        for j in range(enumeration.shape[1] - 1):
            block = enumeration[i : i + 2, j : j + 2]
            if np.array_equal(block, plaq):
                return True
    return False


@pytest.mark.parametrize("lattice_size", range(4, 22, 2))
@pytest.mark.parametrize("snaked", [True, False])
def test_get_plaqs_for_even_odd_enumeration(lattice_size, snaked):
    # Create simple test enumerations
    up = np.arange(lattice_size * lattice_size).reshape(lattice_size, lattice_size)
    down = np.arange(lattice_size * lattice_size, 2 * lattice_size * lattice_size).reshape(lattice_size, lattice_size)

    plaqs = get_plaqs([up, down], snaked=snaked)

    # --- Test 1: All values 0 to 2*L^2 - 1 appear exactly once ---
    all_values = np.sort(plaqs.flatten())
    expected_values = np.arange(2 * lattice_size * lattice_size)
    assert np.array_equal(all_values, expected_values), (
        f"Not all values from 0 to {2 * lattice_size * lattice_size - 1} appear exactly once. Missing: {set(expected_values) - set(all_values)}"
    )

    # --- Test 2: Each plaquette is from a valid 2x2 region in the original matrix ---
    half = len(plaqs) // 2
    up_plaqs = plaqs[:half]
    down_plaqs = plaqs[half:]

    for p in up_plaqs:
        assert are_neighbors(p, up), f"Up plaquette {p} is not a valid 2x2 block in up enumeration"

    for p in down_plaqs:
        assert are_neighbors(p, down), f"Down plaquette {p} is not a valid 2x2 block in down enumeration"
